const KEY='kubochanPanPrintV2';
const yen=n=>'¥'+Number(n||0).toLocaleString('ja-JP');
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{reservations:[],sales:[],products:[
{name:'贅沢ミルク食パン',price:700},{name:'ベーグルサンド',price:370},{name:'クロワッサン',price:300},{name:'あんバター',price:330},{name:'あんフロマージュ',price:330},{name:'ミルク屋さんのメロンパン',price:250},{name:'ミルク屋さんのクリームパン',price:250},{name:'塩バターベーグル',price:250}
]};
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function $(id){return document.getElementById(id)}
function init(){ $('todayText').textContent=new Date().toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'}); ['rDate','sDate','filterDate'].forEach(id=>$(id).value=today()); $('reportMonth').value=today().slice(0,7); $('reportYear').value=new Date().getFullYear(); bind(); render(); if('serviceWorker'in navigator) navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
function bind(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>show(b.dataset.tab,b)); ['rUnit','rQty'].forEach(id=>$(id).oninput=calc); $('rProduct').onchange=()=>{let p=db.products[$('rProduct').value]; if(p){$('rItem').value=p.name;$('rUnit').value=p.price;calc();}}; $('saveReservation').onclick=addReservation; $('saveSale').onclick=addSale; $('saveProduct').onclick=addProduct; $('filterDate').oninput=render; $('sDate').onchange=loadSale; $('printMonthlySales').onclick=()=>{monthlySales(); setTimeout(print,100)}; $('printYearlySales').onclick=()=>{yearlySales(); setTimeout(print,100)}; $('printMonthlyReservations').onclick=()=>{monthlyReservations(); setTimeout(print,100)}; $('printProduction').onclick=()=>{productionReport(); setTimeout(print,100)}; $('downloadBackup').onclick=backup; $('restoreFile').onchange=restore; $('clearAll').onclick=()=>{if(confirm('全データを削除しますか？')){localStorage.removeItem(KEY);location.reload();}};}
function show(id,btn){document.querySelectorAll('.tabPanel').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render();}
function calc(){ $('rAmount').value=Number($('rUnit').value||0)*Number($('rQty').value||1); }
function addReservation(){const r={id:Date.now(),date:$('rDate').value,time:$('rTime').value,name:$('rName').value.trim(),item:$('rItem').value.trim(),unit:Number($('rUnit').value||0),qty:Number($('rQty').value||1),amount:Number($('rAmount').value||0),status:$('rStatus').value,note:$('rNote').value.trim()}; if(!r.date||!r.name||!r.item){alert('日付・お客様名・商品を入力してください');return} db.reservations.push(r); save(); ['rTime','rName','rItem','rUnit','rAmount','rNote'].forEach(id=>$(id).value=''); $('rQty').value=1; $('rProduct').value=''; render(); alert('予約を保存しました');}
function addSale(){const s={id:Date.now(),date:$('sDate').value,amount:Number($('sAmount').value||0),weather:$('sWeather').value,memo:$('sMemo').value.trim()}; if(!s.date){alert('日付を入力してください');return} db.sales=db.sales.filter(x=>x.date!==s.date); db.sales.push(s); save(); render(); alert('売上を保存しました');}
function loadSale(){const s=db.sales.find(x=>x.date===$('sDate').value); $('sAmount').value=s?.amount||''; $('sWeather').value=s?.weather||'晴れ'; $('sMemo').value=s?.memo||'';}
function addProduct(){const name=$('pName').value.trim(); const price=Number($('pPrice').value||0); if(!name){alert('商品名を入力してください');return} db.products.push({name,price}); save(); $('pName').value='';$('pPrice').value='';render();}
function del(type,id){db[type]=db[type].filter(x=>x.id!==id);save();render();}
function delProduct(i){db.products.splice(i,1);save();render();}
function render(){renderProducts();renderHome();renderReservations();renderSales();}
function renderProducts(){ $('rProduct').innerHTML='<option value="">商品を選択</option>'+db.products.map((p,i)=>`<option value="${i}">${esc(p.name)} / ${yen(p.price)}</option>`).join(''); $('productList').innerHTML=db.products.length?db.products.map((p,i)=>`<div class="item"><b>${esc(p.name)}</b><br><span class="price">${yen(p.price)}</span><br><button class="danger small" onclick="delProduct(${i})">削除</button></div>`).join(''):'<div class="empty">商品がありません</div>'; }
function renderHome(){const t=today(); const rs=db.reservations.filter(r=>r.date===t&&r.status!=='キャンセル'); const sale=db.sales.find(s=>s.date===t); $('homeReserveCount').textContent=rs.length+'件'; $('homeReserveAmount').textContent=yen(rs.reduce((a,r)=>a+r.amount,0)); $('homeSales').textContent=yen(sale?.amount||0); $('homePending').textContent=rs.filter(r=>r.status==='未受取').length+'件'; $('todayReservations').innerHTML=rs.length?rs.sort((a,b)=>(a.time||'').localeCompare(b.time||'')).map(resHtml).join(''):'<div class="empty">今日の予約はありません</div>'; const m={}; rs.forEach(r=>m[r.item]=(m[r.item]||0)+Number(r.qty||0)); $('makeList').innerHTML=Object.keys(m).length?Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="item"><b>${esc(k)}</b>　${v}個</div>`).join(''):'<div class="empty">今日作る予約商品はありません</div>';}
function renderReservations(){const f=$('filterDate').value; const list=db.reservations.filter(r=>!f||r.date===f).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)); $('reservationList').innerHTML=list.length?list.map(resHtml).join(''):'<div class="empty">予約がありません</div>';}
function resHtml(r){return `<div class="item"><b>${esc(r.date)} ${esc(r.time)}　${esc(r.name)}</b><span class="pill">${esc(r.status)}</span><br>${esc(r.item)} × ${r.qty}<br><span class="price">${yen(r.amount)}</span><div class="mini">${esc(r.note||'')}</div><button class="small" onclick="toggleStatus(${r.id})">受取切替</button> <button class="danger small" onclick="del('reservations',${r.id})">削除</button></div>`}
function toggleStatus(id){const r=db.reservations.find(x=>x.id===id); if(r){r.status=r.status==='受取済み'?'未受取':'受取済み';save();render();}}
function renderSales(){const list=[...db.sales].sort((a,b)=>b.date.localeCompare(a.date)); $('salesList').innerHTML=list.length?list.map(s=>`<div class="item"><b>${esc(s.date)}</b><span class="pill">${esc(s.weather)}</span><br><span class="price">${yen(s.amount)}</span><div class="mini">${esc(s.memo||'')}</div><button class="danger small" onclick="del('sales',${s.id})">削除</button></div>`).join(''):'<div class="empty">売上データがありません</div>';}
function monthlySales(){const ym=$('reportMonth').value; const rows=db.sales.filter(s=>s.date.startsWith(ym)).sort((a,b)=>a.date.localeCompare(b.date)); const sum=rows.reduce((a,s)=>a+s.amount,0); const avg=rows.length?Math.round(sum/rows.length):0; $('printArea').innerHTML=`<div class="printDoc"><h1>月間売上表 ${ym}</h1><div class="summary"><div>合計<br><b>${yen(sum)}</b></div><div>営業日数<br><b>${rows.length}日</b></div><div>平均<br><b>${yen(avg)}</b></div></div><table><tr><th>日付</th><th>売上</th><th>天気</th><th>メモ</th></tr>${rows.map(s=>`<tr><td>${esc(s.date)}</td><td>${yen(s.amount)}</td><td>${esc(s.weather)}</td><td>${esc(s.memo)}</td></tr>`).join('')}</table></div>`;}
function yearlySales(){const y=String($('reportYear').value); const months=Array.from({length:12},(_,i)=>`${y}-${String(i+1).padStart(2,'0')}`); const data=months.map(m=>{let rows=db.sales.filter(s=>s.date.startsWith(m));let sum=rows.reduce((a,s)=>a+s.amount,0);return{m,days:rows.length,sum}}); const total=data.reduce((a,x)=>a+x.sum,0); const max=Math.max(1,...data.map(x=>x.sum)); $('printArea').innerHTML=`<div class="printDoc"><h1>年間売上表 ${y}年</h1><div class="summary"><div>年間合計<br><b>${yen(total)}</b></div><div>月平均<br><b>${yen(Math.round(total/12))}</b></div><div>記録月数<br><b>${data.filter(x=>x.sum>0).length}ヶ月</b></div></div><table><tr><th>月</th><th>営業日数</th><th>売上</th><th>グラフ</th></tr>${data.map(x=>`<tr><td>${x.m}</td><td>${x.days}日</td><td>${yen(x.sum)}</td><td><div class="bar" style="width:${Math.round(x.sum/max*100)}%"></div></td></tr>`).join('')}</table></div>`;}
function monthlyReservations(){const ym=$('reportMonth').value; const rows=db.reservations.filter(r=>r.date.startsWith(ym)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)); $('printArea').innerHTML=`<div class="printDoc"><h1>月間予約一覧 ${ym}</h1><table><tr><th>日付</th><th>時間</th><th>お客様名</th><th>商品</th><th>個数</th><th>金額</th><th>状態</th><th>備考</th></tr>${rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.time)}</td><td>${esc(r.name)}</td><td>${esc(r.item)}</td><td>${r.qty}</td><td>${yen(r.amount)}</td><td>${esc(r.status)}</td><td>${esc(r.note)}</td></tr>`).join('')}</table></div>`;}
function productionReport(){const ym=$('reportMonth').value; const map={}; db.reservations.filter(r=>r.date.startsWith(ym)&&r.status!=='キャンセル').forEach(r=>map[r.item]=(map[r.item]||0)+Number(r.qty||0)); const rows=Object.entries(map).sort((a,b)=>b[1]-a[1]); $('printArea').innerHTML=`<div class="printDoc"><h1>製造数集計 ${ym}</h1><table><tr><th>商品</th><th>合計個数</th></tr>${rows.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v}個</td></tr>`).join('')}</table></div>`;}
function backup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='kubochan-pan-backup-'+today()+'.json'; a.click();}
function restore(e){const file=e.target.files[0]; if(!file)return; const fr=new FileReader(); fr.onload=()=>{try{db=JSON.parse(fr.result); save(); render(); alert('復元しました');}catch{alert('復元できませんでした');}}; fr.readAsText(file);}
init();
