document.addEventListener('DOMContentLoaded',init);
function init(){setDates();bindNav();bindForms();checkLock();renderAll();registerSW();checkUpdateNotice();}
function setDates(){document.getElementById('todayLabel').textContent=new Date().toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'});['rDate','filterDate','productionDate','saleDate'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=today()});document.getElementById('analyticsMonth').value=today().slice(0,7);document.getElementById('analyticsYear').value=new Date().getFullYear();document.getElementById('versionLabel').textContent=APP_VERSION}
function bindNav(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));renderAll();}
function bindForms(){document.getElementById('addItemBtn').onclick=()=>addItemRow();document.getElementById('saveReserveBtn').onclick=saveReservation;document.getElementById('filterDate').oninput=renderReservations;document.getElementById('filterName').oninput=renderReservations;document.getElementById('productionDate').oninput=renderProduction;document.getElementById('saveSaleBtn').onclick=saveSale;document.getElementById('lineProductionBtn').onclick=shareProduction;document.getElementById('printProductionBtn').onclick=()=>window.print();document.getElementById('backupBtn').onclick=backup;document.getElementById('restoreFile').onchange=restore;document.getElementById('savePasswordBtn').onclick=savePassword;document.getElementById('removePasswordBtn').onclick=removePassword;document.getElementById('unlockBtn').onclick=unlock;document.getElementById('forceUpdateBtn').onclick=forceUpdate;document.getElementById('refreshBtn').onclick=forceUpdate;document.getElementById('clearCacheBtn').onclick=clearCaches;document.getElementById('applyUpdateBtn').onclick=applyUpdate;document.getElementById('laterUpdateBtn').onclick=dismissUpdate;addItemRow();}
function productOptions(){return state.products.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} / ${yen(p.price)}</option>`).join('')}
function addItemRow(item={}){const wrap=document.getElementById('itemRows');const div=document.createElement('div');div.className='item-row';div.innerHTML=`<div class="item-grid"><label>商品<select class="itemProduct"><option value="">選択</option>${productOptions()}</select></label><label>個数<input class="itemQty" type="number" min="1" value="${item.qty||1}"></label><label>金額<input class="itemAmount" type="number" min="0" value="${item.amount||0}"></label><button class="ghost removeItem">削除</button></div>`;wrap.appendChild(div);const sel=div.querySelector('.itemProduct');const qty=div.querySelector('.itemQty');const amt=div.querySelector('.itemAmount');if(item.productId)sel.value=item.productId;sel.onchange=()=>{const p=state.products.find(x=>x.id===sel.value);if(p)amt.value=Number(p.price)*Number(qty.value||1)};qty.oninput=()=>{const p=state.products.find(x=>x.id===sel.value);if(p)amt.value=Number(p.price)*Number(qty.value||1)};div.querySelector('.removeItem').onclick=()=>div.remove();}
function saveReservation(){const rows=[...document.querySelectorAll('.item-row')].map(r=>{const p=state.products.find(x=>x.id===r.querySelector('.itemProduct').value);return p?{productId:p.id,name:p.name,category:p.category||'',qty:Number(r.querySelector('.itemQty').value||1),amount:Number(r.querySelector('.itemAmount').value||0)}:null}).filter(Boolean);if(!rName.value||!rows.length){alert('お客様名と商品を入力してください');return}state.reservations.push({id:uid(),date:rDate.value,time:rTime.value,name:rName.value,items:rows,status:rStatus.value,note:rNote.value});persist();rName.value='';rNote.value='';itemRows.innerHTML='';addItemRow();toast('保存しました');renderAll();}
function renderReservations(){const fd=filterDate.value, fn=filterName.value.trim();const list=state.reservations.filter(r=>(!fd||r.date===fd)&&(!fn||r.name.includes(fn))).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));reserveList.innerHTML=list.map(r=>`<div class="list-card"><b>${esc(r.time||'')} ${esc(r.name)}</b> <span class="status">${esc(r.status)}</span><div class="soft-text">${r.items.map(i=>`${esc(i.name)}×${i.qty}`).join(' / ')}<br>合計 ${yen(r.items.reduce((a,i)=>a+i.amount,0))}</div><select onchange="changeStatus('${r.id}',this.value)"><option ${r.status==='未受取'?'selected':''}>未受取</option><option ${r.status==='受取済み'?'selected':''}>受取済み</option><option ${r.status==='キャンセル'?'selected':''}>キャンセル</option></select><button class="ghost full" onclick="deleteReservation('${r.id}')">削除</button></div>`).join('')||'<p class="soft-text">予約はありません</p>'}
function changeStatus(id,v){const r=state.reservations.find(x=>x.id===id);if(r){r.status=v;persist();renderAll()}}
function deleteReservation(id){if(confirm('削除しますか？')){state.reservations=state.reservations.filter(r=>r.id!==id);persist();renderAll()}}
function productionFor(date){const map={};state.reservations.filter(r=>r.date===date&&r.status!=='キャンセル').forEach(r=>r.items.forEach(i=>{map[i.name]??={qty:0,category:i.category||'その他',details:[]};map[i.name].qty+=Number(i.qty||0);map[i.name].details.push(`${r.time||''} ${r.name}：${i.qty}`)}));return map}
function renderProduction(){const d=productionDate.value||today();const map=productionFor(d);productionList.innerHTML=Object.entries(map).map(([name,v])=>`<div class="list-card"><div class="prod-line"><b>${esc(name)}</b><b>${v.qty}個</b></div><div class="prod-detail">${v.details.map(esc).join('<br>')}</div></div>`).join('')||'<p class="soft-text">製造予定はありません</p>';}
function renderHome(){const d=today();const rs=state.reservations.filter(r=>r.date===d);const reserveSales=rs.filter(r=>r.status!=='キャンセル').reduce((a,r)=>a+r.items.reduce((s,i)=>s+i.amount,0),0);const sale=state.sales.find(s=>s.date===d)||{};homeReserveCount.textContent=rs.length+'件';homeReserveSales.textContent=yen(reserveSales);homeShopSales.textContent=yen(sale.shop||0);homeTotalSales.textContent=yen(reserveSales+Number(sale.shop||0));const map=productionFor(d);homeProduction.innerHTML=Object.entries(map).slice(0,5).map(([n,v])=>`<div class="prod-line"><span>${esc(n)}</span><b>${v.qty}個</b></div>`).join('')||'<p class="soft-text">今日の製造予定はありません</p>';const ly=new Date(d);ly.setFullYear(ly.getFullYear()-1);const lys=ly.toISOString().slice(0,10);const last=state.sales.find(s=>s.date===lys);lastYearBox.innerHTML=last?`${lys}<br>天気：${esc(last.weather||'-')}<br>売上：${yen(last.shop||0)}<br>メモ：${esc(last.memo||'-')}`:'去年の今日のデータはまだありません';}
function saveSale(){const data={date:saleDate.value,shop:Number(shopSale.value||0),weather:weather.value,visitors:Number(visitors.value||0),memo:saleMemo.value};state.sales=state.sales.filter(s=>s.date!==data.date);state.sales.push(data);persist();toast('売上を保存しました');renderAll();}
function renderSales(){salesList.innerHTML=state.sales.sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<div class="list-card"><b>${s.date}</b><br>販売売上 ${yen(s.shop)} / 天気 ${esc(s.weather||'')}</div>`).join('')||'<p class="soft-text">売上データはありません</p>'}
function renderAnalytics(){const ym=analyticsMonth.value;const monthRs=state.reservations.filter(r=>r.date.startsWith(ym));const prod={};monthRs.forEach(r=>r.items.forEach(i=>{prod[i.name]??={qty:0,sales:0};prod[i.name].qty+=i.qty;prod[i.name].sales+=i.amount}));analyticsBox.innerHTML=Object.entries(prod).sort((a,b)=>b[1].sales-a[1].sales).map(([n,v])=>`<div class="prod-line"><span>${esc(n)} ${v.qty}個</span><b>${yen(v.sales)}</b></div>`).join('')||'<p class="soft-text">データはありません</p>'}
function shareProduction(){const d=productionDate.value||today();const map=productionFor(d);const text=`${d} 製造リスト\n`+Object.entries(map).map(([n,v])=>`${n} ${v.qty}個`).join('\n');location.href='https://line.me/R/msg/text/?'+encodeURIComponent(text)}
function backup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kubochan-pan-backup-'+today()+'.json';a.click();}
function restore(e){const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const data=JSON.parse(rd.result);Object.assign(state,data);persist();renderAll();toast('復元しました')}catch(err){alert('復元できませんでした')}};rd.readAsText(f)}
function savePassword(){state.settings.password=newPassword.value;persist();toast('パスワードを設定しました')}
function removePassword(){state.settings.password='';persist();toast('パスワードを解除しました')}
function checkLock(){if(state.settings.password)passwordScreen.classList.remove('hidden')}
function unlock(){if(passwordInput.value===state.settings.password)passwordScreen.classList.add('hidden');else alert('パスワードが違います')}
function renderAll(){renderHome();renderReservations();renderProduction();renderSales();renderAnalytics()}
function toast(msg){const el=document.createElement('div');el.className='update-card';el.innerHTML=`<div class="update-icon">✅</div><div><b>${esc(msg)}</b></div>`;document.body.appendChild(el);setTimeout(()=>el.remove(),1600)}
async function registerSW(){if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('service-worker.js?v='+APP_VERSION)}catch(e){}}}
async function clearCaches(){if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}localStorage.setItem(APP_KEYS.update,JSON.stringify({lastDismiss:Date.now(),version:APP_VERSION}));toast('キャッシュを削除しました')}
async function forceUpdate(){await clearCaches();location.href=location.pathname+'?v='+Date.now()}
function dismissUpdate(){saveJSON(APP_KEYS.update,{lastDismiss:Date.now(),version:APP_VERSION});updateNotice.classList.add('hidden')}
function applyUpdate(){dismissUpdate();forceUpdate()}
function checkUpdateNotice(){const info=loadJSON(APP_KEYS.update,{lastDismiss:0,version:''});const eight=8*60*60*1000;if(Date.now()-Number(info.lastDismiss||0)<eight&&info.version===APP_VERSION)return; if(info.version&&info.version!==APP_VERSION){updateText.textContent=`Ver.${APP_VERSION} を取得できます。`;updateNotice.classList.remove('hidden')} saveJSON(APP_KEYS.update,{lastDismiss:Date.now(),version:APP_VERSION});}
